[build]
  command = "jekyll build"
  publish = "_site"

[dev] 
  command = "bundle exec jekyll server --trace" # Command to start your dev server
  port = 4000 # Port that the dev server will be listening on
  publish = "." # Folder with the static content for _redirect file

[build.environment]
  JEKYLL_ENV = "production"

[[redirects]]
  from = "http://alia-aliapourvous.netlify.com/*"
  to = "https://aliapourvous.com/:splat"
  status = 301
  force = true